-- 코드를 입력하세요
SELECT T2.NAME, T2.DATETIME
FROM ANIMAL_INS T2
WHERE T2.ANIMAL_ID 
NOT IN (SELECT A.ANIMAL_ID FROM ANIMAL_INS A, ANIMAL_OUTS B
     WHERE A.ANIMAL_ID = B.ANIMAL_ID)
     ORDER BY T2.DATETIME ASC
     LIMIT 3;
